### ISSUE TITLE
配置Blackhole 为什么不起作用

### ISSUE THREAD

**Issue by dytiz** [V2Ray-Android/Actinium#15]
请教一下，我想实现V2Ray广告拦截的效果，但是好像没什么用，配置如下：
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "adblock"
    }
  ],
"routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "domain": [
            "baidu.com",
            "google.com"
          ],
          "outboundTag": "adblock"
        },
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  },

**Comment by cnperi** [comment]
解决了吗？我也有这个疑惑。

**Comment by dytiz** [comment]
no

**Comment by cnperi** [comment]
@dytiz 参见https://github.com/v2ray/v2ray-core/issues/425
