### ISSUE TITLE
请问最新版怎么下载？

### ISSUE THREAD

**Issue by walasix** [V2Ray-Android/Actinium#18]
小白请教一下，最新版的都没在release里面，也没有download的链接，怎么下载啊？

**Comment by vc12345679** [comment]
最简单的办法，google play 上申请 actinium 的 beta版 试用

**Comment by walasix** [comment]
@vc12345679 谢谢。您意思是说最新版目前都是beta版的？还没有发布，所以不供下载是吧？

**Comment by vc12345679** [comment]
@walasix 我一直追随的google play上的beta版，更新挺及时的，没从github上下载编译过…

**Comment by walasix** [comment]
@vc12345679 问题是Google play上的国内没法下载和安装啊。。怎么破

**Comment by vc12345679** [comment]
@walasix  源码都在这儿，自己编译也行啊

**Comment by walasix** [comment]
@vc12345679 通过apk downloader之类的网站下载play商店的actinium，但在手机上安装时提示“应用未安装”，请问怎么解决呢？

**Comment by xiaokangwang** [comment]
@walasix  你需要看logcat来得到具体的错误信息
