### ISSUE TITLE
有没有兴趣合作

### ISSUE THREAD

**Issue by lovetcp** [V2Ray-Android/Actinium#20]
现在我们公司希望通过VPN技术方式在手机端实现应用代理，但是同时需要根据APP应用标识分发到不同的代理服务器上，本来想利用V2的路由功能来简单实现分发，但是由于目前的开源版本不支持，能否合作来实现这个需求。
基本需求：
手机端有几个应用，需要通过VPN实现代理，但是之前的SS只能实现一点代理，无法将根据应用或者手机号码进行定制化的代理到不同的代理服务器，然后再访问真实的应用服务器。

**Comment by xiaokangwang** [comment]
如果是想实现分应用代理的话，应该需要在tun2socks进行相应的改动，将发起连接的进程名一起发送到V2Ray。

如果在设备上可以使用root的话，用iptable实现应该是比较方便的。

**Comment by xiaokangwang** [comment]
你是否想先尝试使用iptable完成对应的功能？

**Comment by lovetcp** [comment]
在手机侧很难获取到ROOT权限的，只能通过安卓操作系统形成虚拟网关，例如socketshadows那样建立VPN，将手机应用访问信息进行拦截，然后转发到一个端口上，默认是1080端口，然后再考虑如何能够根据应用进行分发到指定的代理服务器上，通过代理服务器访问internet网。

**Comment by lovetcp** [comment]
不知能否合作解决这个问题，因为我们的人无法知道GO语言及网络协议中附加信息传输。

**Comment by xiaokangwang** [comment]
我自己没有事件参与搞这个, 如果有其他开发者愿意参与可以继续交流。

**Comment by liberal-boy** [comment]
@lovetcp Android 的 VPNService 无法判断请求来自哪个应用（用户），iptables 似乎是唯一可行的方案。

**Comment by xiaokangwang** [comment]
大概思路就是改一下tun2socks(C)的代码把进出的tcp端口发送过来，然后再改libv2ray(Go),v2ray-core(Go)支持按来源转发。我暂时懒得搞。。。

**Comment by liberal-boy** [comment]
@xiaokangwang Android 同一时间内只能开启一个 VpnService，所以 tun2socks 也是只用一个监听端口。所以依靠 VpnService 进行按应用转发基本无解。如果是别人做的应用，iptables 似乎是毕竟简单的办法，如果是自己的应用就好办，直接设置 http 代理即可。

**Comment by walasix** [comment]
@liberal-boy 大神，请问最新版在哪儿能下载啊？小白不会自行编译。。谢谢大神！

**Comment by liberal-boy** [comment]
@walasix play 商店有

**Comment by walasix** [comment]
@liberal-boy 谢谢大神回复，我看到play商店有，但是qiang内没法在play下载啊？

**Comment by walasix** [comment]
@liberal-boy 大神， 通过apk downloader之类的网站下载play商店的actinium，但在手机上安装时提示“应用未安装”，试了几次都无法安装，请问怎么解决呢？

**Comment by lovetcp** [comment]
可以提供相关费用的，费用方面可以商量，基本需求如下：
   1、能够对接入的应用进行黑白名单控制，如果是符合接入条件的应用，就能够进入代理中进行应用转发，不符合接入的还是走原来的网络访问。
  2、手机侧的代理能够根据应用标识按照路由规则进行代理转发，转发到不同的服务器。
  3、转发的路由规则是通过管理服务端进行提供。
  4、协议要能够支撑常见的协议：HTTP/HTTPS/SOCKT(TCP/UDP).
  5、在代理服务端需要形成相关的手机访问日志记录
 


周永强
电子渠道事业部|湖南科创信息技术股份有限公司
Address  长沙市岳麓区（高新区）青山路678号
Mobile   13973123657
Tel          0731-83757888/837579999
Fax         0731-82068637
E-mail     2725262@qq.com
 
发件人： Xiaokang Wang
发送时间： 2017-03-13 18:31
收件人： V2Ray-Android/Actinium
抄送： lovetcp; Mention
主题： Re: [V2Ray-Android/Actinium] 有没有兴趣合作 (#20)
大概思路就是改一下tun2socks(C)的代码把进出的tcp端口发送过来，然后再改libv2ray(Go),v2ray-core(Go)支持按来源转发。我暂时懒得搞。。。

**Comment by lovetcp** [comment]
那个 V2Ray-Android/AndroidLibV2ray的代码有好久没有更新了。
