### ISSUE TITLE
这个客户端能否支撑根据IP路由到不同V2服务器

### ISSUE THREAD

**Issue by lovetcp** [V2Ray-Android/Actinium#22]

**Comment by lovetcp** [comment]
这个客户端能否支撑根据IP路由到不同V2服务器，我希望访问IP1到代理到服务器1，访问IP2的代理到服务器2

**Comment by xiaokangwang** [comment]
这个可以通过rule实现，这部分和v2ray-core是相同的

**Comment by lovetcp** [comment]
我拿这个没有成功过，能否提供相关例子。

**Comment by lovetcp** [comment]
我看了配置，那个都是outbound都是direct，没有其它TAG标签。

**Comment by lovetcp** [comment]
这个工程提供的配置文件都是freedom模式，没有通过服务器中转的。能否提供一部分通过中转的例子。

**Comment by lovetcp** [comment]
提供的默认配置文件中RULES不起作用。

**Comment by lovetcp** [comment]
根据默认的配置文件调整的一下配置文件，无法生效启动，客户端使用的0.6.1的版本。
{
  "port": 10809,
  "log": {
    "loglevel": "warning",
    "access":"",
    "error":""
  },
  "inbound": {
    "protocol": "socks",
    "listen": "127.0.0.1",
    "settings": {
      "auth": "noauth",
      "udp": true
    }
  },
  "inboundDetour": [],
  "outbound": {
    "protocol": "shadowsocks",
    "tag": "server1",
    "settings": {
    "servers": [
      {
        "address": "61.50.245.179",
        "port": 8053,
        "method": "aes-256-cfb",
        "password": "1234556676663",
        "ota": false
      }
    ]}
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "port": "1-52",
          "outboundTag": "server1"
        },
        {
          "type": "field",
          "port": "54-79",
          "outboundTag": "server1"
        },
        {
          "type": "field",
          "port": "81-442",
          "outboundTag": "server1"
        },
        {
          "type": "field",
          "port": "444-65535",
          "outboundTag": "server1"
        },
        {
          "type": "chinasites",
          "outboundTag": "server1"
        },
        {
          "type": "field",
          "domain": [
            "*.5ivdo.com"
          ],
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "server1"
        },
        {
          "type": "chinaip",
          "outboundTag": "server1"
        }
      ]
    }
  },
  "transport": {},
  "#lib2ray": {
    "enabled": true,
    "listener": {
      "onUp": "#none",
      "onDown": "#none"
    },
    "env": [
      "V2RaySocksPort=10809"
    ],
    "render": [],
    "escort": [],
    "vpnservice": {
      "Target": "${datadir}tun2socks",
      "Args": [
        "--netif-ipaddr",
        "26.26.26.2",
        "--netif-netmask",
        "255.255.255.0",
        "--socks-server-addr",
        "127.0.0.1:$V2RaySocksPort",
        "--tunfd",
        "3",
        "--tunmtu",
        "1500",
        "--sock-path",
        "/dev/null",
        "--loglevel",
        "4",
        "--enable-udprelay"
      ],
      "VPNSetupArg": "m,1500 a,26.26.26.1,24 r,0.0.0.0,0"
    }
  }
}

**Comment by lovetcp** [comment]
这个怎么没有结果了，能否给一份实际验证过的例子给我参考一下。

**Comment by lovetcp** [comment]
请问谁拿这个APP验证过这个问题？能否提供一份例子给我参考一下。

**Comment by xiaokangwang** [comment]
这部分的功能主要是和v2ray-core有关，请您阅读文档。https://www.v2ray.com/

**Comment by liberal-boy** [comment]
根据IP转发是没有问题的，如果出现问题，请检查配置文件是否正确，并且我不了解您确认规则是否生效的方法。但是由于DNS问题，暂不支持根据域名转发。
