### ISSUE TITLE
一旦开启服务， 应用马上停止运行

### ISSUE THREAD

**Issue by yangguodaxia** [V2Ray-Android/Actinium#26]
安卓版本是7.1.2
应用是在Apkpure下载的。

**Comment by AOne98** [comment]
我也遇到这个问题了。我是华为荣耀6p，您的也是华为手机不？

**Comment by xiaokangwang** [comment]
这个问题和 #29 应该是一个，转移到那里处理。如果有更加详细的信息说明两个issue中出现的不是一个问题，请重新打开此issue。
