### ISSUE TITLE
不可以监听0.0.0.0

### ISSUE THREAD

**Issue by LovingYoung** [V2Ray-Android/Actinium#30]
配置文件监听IP为0.0.0.0，但是导入之后就转换成了127.0.0.1。
希望可以监听0.0.0.0来将Proxy共享出来给一些Console用。
有什么方法可以解决吗

**Comment by xiaokangwang** [comment]
这种比较高级的功能需要使用V2RayGO，Ac因为对简易使用场景优化的原因会失去一些自定义的机会。

**Comment by LovingYoung** [comment]
明白，谢谢
