### ISSUE TITLE
There is no delete menu in the UI. i want to delete the wrong profile

### ISSUE THREAD

**Issue by netroby** [V2Ray-Android/Actinium#36]
There is no delete menu in the UI. i want to delete the wrong profile

**Comment by gregist** [comment]
use long press.

**Comment by netroby** [comment]
long press only have edit button

_Sent from my Xiaomi Mi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by netroby** [comment]
![_20170801074724](https://user-images.githubusercontent.com/278153/28803269-f07e8488-768d-11e7-9e7f-267a292b7005.png)

**Comment by cnperi** [comment]
plz long press the others.

**Comment by netroby** [comment]
Yes, i see it. 

But .. what the fuck you guys hide the delete button so deep...

And once i choose delete, it just really delete, not confirm pop out.

It shall be a confirm pop. let me decided

**Comment by netroby** [comment]
Problem still here. UI need improve. but i can close this issue
