### ISSUE TITLE
kcp connection won't stream videos

### ISSUE THREAD

**Issue by gregist** [V2Ray-Android/Actinium#37]
I am using v2rayN on Windows (works nomally) and the config file I imported to Actinium contains the following lines:

`  "inbound": {
    "port": 1081,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1",
      "clients": null
    },
    "streamSettings": null
  },
  "outbound": {
    "tag": "agentout",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "****",
          "port": ****,
          "users": [
            {
              "id": "my-id",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "kcp",
      "security": "",
      "tcpSettings": null,
      "kcpSettings": {
        "mtu": 1350,
        "tti": 50,
        "uplinkCapacity": 12,
        "downlinkCapacity": 100,
        "congestion": false,
        "readBufferSize": 2,
        "writeBufferSize": 2,
        "header": {
          "type": "none",
          "request": null,
          "response": null
        }
      },
      "wsSettings": null
    },
    "mux": {
      "enabled": true
    }
  },
  "inboundDetour": null,
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {
        "response": null
      },
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      },
      "tag": "blockout"
    }
  ],`

I can connect to my server and browse webpages normally, however I have problem streaming videos.

Android version: PureNuxus 7.1.2

**Comment by zhangzitong719** [comment]
我下載過Actinium並連接了它  然後打開推特和臉書一看，連別人發的視頻帖子都看不了，這是怎麼回事？ 麻煩給我zzt327@gmail.com回信,謝謝！
