### ISSUE TITLE
[BUG] vpn 被动关闭后引出的

### ISSUE THREAD

**Issue by ToutyRater** [V2Ray-Android/Actinium#4]
版本：0.3.1
手机：Android 6.0.1
问题：先放图
![photo_2016-08-28_22-35-12](https://cloud.githubusercontent.com/assets/20978410/18034523/b64f99e6-6d2e-11e6-90cc-a73e2d0e7f99.jpg)
当 actinium 运行时，在ss启用，再关闭，然后在 actinium 点 fab 会无法开启 vpn，接着就出现如[#2](https://github.com/V2Ray-Android/Actinium/issues/2)的情况
另外，这个bug似乎是随机出现的，每当我特意测试时就不会重现，然而这个现象已经出现多次，确定与没有关闭vpn就开ss有关

**Comment by liberal-boy** [comment]
这问题发生有点诡异，暂时找不到原因。😂😂😂

**Comment by ToutyRater** [comment]
很难重现，从我发了这个issue到现在就没有出现过了

**Comment by ToutyRater** [comment]
经过一下午的测试，终于找到了快速重现这个 bug 的方法：

1. 运行 actinium，点 fab 开启 vpn
2. 切换到 ss/ssr，点 fab，原来的 vpn 被关闭并开启 ss/ssr 的 vpn
3. **点 ss/ssr 的 fab 之后立即切换到 actinium （不要犹豫）**
4. 这个时候就看到如图的情况，再点 actinium 的 fab 是无法开启 vpn 的，就如 [#2](https://github.com/V2Ray-Android/Actinium/issues/2)


有几点说明：
* 按照以上的方法操作不是 100% 成功，基本有 1/2 的概率会触发这个 bug（没有统计）。
* 这个 bug 并不是只有这样的操作步骤才能触发，在过去的数次发现这个 bug 的是这样的：先用 actinium ，过一段时间用 ss ，又过一段时间又想用 actinium 然后就发现了这个现象。
* 这个 bug 跟 [#2](https://github.com/V2Ray-Android/Actinium/issues/2)息息相关，因为这我的测试当中发现只要出现了这个 bug 就会出现 [#2](https://github.com/V2Ray-Android/Actinium/issues/2) 的 bug。
* 按照以上操作方法，有可能没有触发这个 bug （配置前的圆点是正常的彩色），但已经极大可能地触发了 [#2](https://github.com/V2Ray-Android/Actinium/issues/2) 的 bug（没法开启vpn）

**Comment by liberal-boy** [comment]
@ToutyRater 0.5.3应该已经解决这个问题
