### ISSUE TITLE
点击编辑直连列表后闪退

### ISSUE THREAD

**Issue by Jeffwhen** [V2Ray-Android/Actinium#7]
Android 5.1，arm v7a 指令集。

**Comment by liberal-boy** [comment]
请截取日志上传，或在应用崩溃时选择向google报告

**Comment by Jeffwhen** [comment]
日志存哪里呢？不知道是不是因为国行没有谷歌服务所以 FC 时候没有选择报告的选项。

**Comment by liberal-boy** [comment]
70d8386 该故障应该已经在 0.6.1 中得到修复。
