### ISSUE TITLE
Actinium 耗电测试报告

### ISSUE THREAD

**Issue by ToutyRater** [V2Ray-Android/Actinium#9]
经过长时间地使用 Actinium，感觉似乎会比较耗电。为了验证心中的想法是否正确，我做了个并不严格的测试。
测试机情况：
* 手机系统：Android 6.0.1
* 手机卡：
  - SIM1：中国移动 4G
  - SIM2：中国联通 2G
* Actinium 版本：0.5.2

测试的一些问题：
- 由于环境因素的限制，无法确保每次测试的初始电量、测试时间、信号强度等变量一致，但后台运行的软件基本相同
- 因为没有测试手机的相关经验，所以暂时只能测试手机灭屏时的耗电情况
- 由于个人原因，无法引入 Shadowsock / Shadowsock-rss / V2RayGo 做为对比

关于以上问题，如有必要，我将会做出改进的测试

测试说明：
- 第一天、第二天，均开启Actinium，第三天关闭 Actinium
- 三天均开启中国移动 TLE 网络
- 截图的红色直线为个人添加，以便于分析结果

以下截图是三天的测试结果：
第一天
![g1](https://cloud.githubusercontent.com/assets/20978410/19025545/b2257ff6-8909-11e6-8aae-d82f58af56f3.jpg)

第二天
![g2](https://cloud.githubusercontent.com/assets/20978410/19025563/03328ae2-890a-11e6-84ba-4f5b14c1059e.jpg)

第三天
![g3](https://cloud.githubusercontent.com/assets/20978410/19025581/27dc34c4-890a-11e6-833f-a66f2b590d23.jpg)

结果：
- 第一天
  - 时间：约 8.5 h
  - 信号情况： 大部分时间强度中
  - 唤醒：长时间、频繁唤醒
  - 电量
     - 初始电量：66%
     - 最终电量：15%
     - 耗电量：50%
- 第二天
  - 时间：约 7.5 h
  - 信号情况： 大部分时间强度优
  - 唤醒：长时间、频繁唤醒
  - 电量
     - 初始电量：83%
     - 最终电量：48%
     - 耗电量：35%
- 第三天
  - 时间：约 7.5 h
  - 信号情况： 基本为良
  - 唤醒：基本不唤醒
  - 电量
     - 初始电量：74%
     - 最终电量：70%
     - 耗电量：4%

分析：
- 由第一天与第二天的对比可知，信号强度高造成耗电量大
- 第二天的信号情况优于第三天，但耗电量远高第三天，可以说明 actinium 造成了较大的耗电量

`[注]`：个人猜测耗电问题可能是由于LibV2Ray引起的，因为没有V2RayGo进行测试无法确定。暂时粗糙地测试了 Actinium，初步证明 Actinium 确实会有耗电量大的问题。由于个人原因无法进行更加合理、科学、详细的测试。如果需要更加详细、合理的测试信息，我可以进一步进行测试。

**Comment by liberal-boy** [comment]
我数学不好😱第三天的 7.5 h 是怎么来的？
话说你的 detail 里面为什么没有最关键的保持唤醒时间？
表示我的机器上长时间开着 Actinium 关屏待机，并没有出现频繁唤醒。
建议再横向对比一下 Shadowsocks。

**Comment by ToutyRater** [comment]
> 但是我怀疑他的系统不干净，我长时间开着actinium关屏待机基本上没有唤醒的

对于你的怀疑，我做一个补充说明：
- 我的手机上大部分是非国产应用，其中有一半是google全家桶，不能说不是国产的就一定好，但非国产的质量高不流氓要比国产的多得多是公认的，当然，我无法排除是这些app在搞怪
- 我的手机也有国产应用，只有3个：qq，微信及某省移动营业厅。也不排除是这些app在唤醒的可能
- 我昨天又做了新的测试：开着actinium，但关闭了移动数据，耗电情况与开数据关actinium基本相同。如果是我系统不干净有其它应用唤醒那么开数据关actinium也不怎么耗电这点说不通。但如果是actinium的锅那么在你手机上不耗电也说不通

基于以上几点，确实无法证明是什么原因导致的。另外，现在我正在刷机（干净的系统），我会在这几日内做进一步测试（我将会尽量控制好变量）。
（在这里回复一是好组织语言，二是我要保持帐户之间的独立）

**感谢你的付出**

**Comment by ToutyRater** [comment]
@liberal-boy 
第三天的7.5h是因为我前天晚上12点20多睡的，第二天8点起，所以约7.5h。
保持唤醒时间我不清楚是什么
我现在已经刷机完了，会进行一次对比的，之前没做是因为手机没法用ss

**Comment by v2ray** [comment]
第三天的图大约只有3个小时，不过从曲线来看依然比前两天要省电。

从电量消耗来看， Actinium 的耗电量和传输的数据成正比。不过我没法估计出具体传输了多少量的数据。由于Actinium本身不会主动发送数据，那么在开启Actinium的时候其它程序发出了更多的数据。于是推断其它程序中有些数据请求失败，然后在重试。

简单的调整方式是在 Actinium 中配置一个 socks <-> freedom 的连接，使数据全部都不走代理服务器，以减小代理服务器的影响。

**Comment by ToutyRater** [comment]
@v2ray 
你应该是看错了，在第三天的图里，第一根虚线是10月3号0点，第二根虚线是10月4号0点，两者之间有个刻度是3号16点，从图中来看，灭屏的时间长度约是3号0点至16点的一半，也差不多等于3号16点到4号0点的长度，因此，约7.5h的说法不是错误。

`推断其它程序中有些数据请求失败，然后在重试。`这是我没有想到的，多谢你的提醒。配置socks <-> freedom 也是很好的想法，多谢你的建议，我会进一步求证

**Comment by liberal-boy** [comment]
@v2ray 确实是，中间的 4 PM 是第二天下午😂

**Comment by ToutyRater** [comment]
刷机之后，actinium更新到了0.5.3，经过几天测试，结果：
- 除了actinium，其它所有非系统应用全部冻结，结果非常耗电，熄屏状态时刻都在唤醒
- 使用 shadowsocks，版本3.0.4，熄屏时基本没有唤醒，耗电少
- 按 @v2ray 所说，将outbound改成freedom，耗电情况如shadowsocks，于是猜测可能就像 @v2ray 说的那样 “其它程序中有些数据请求失败，然后在重试”，如果这个猜测是正确的，由于第一条的原因，那么会是系统或系统应用的锅
- outbound改成了vmess，依然耗电。又想到一点，我的v2ray和ss是在同一个服务器上，而且ss是用v2ray开的，如果真如 @v2ray 那样的猜测，同样是代理，那么按理说ss也会耗电才对。也就是说，出现这个问题有可能是vmess协议的锅
- 后来，注意到我在v2ray使用的是mkcp，于是反复对比测试tcp和mkcp，结果是kcp就如前面说的那样异常耗电，而tcp基本不耗电

说了这么多，结论是使用mkcp会造成耗电问题。但我觉得还没完，因为这个问题只在我手机上出现，样本量太少，结论不算可靠。而且如果结论成立，那么是什么原因造成使用mkcp会出现耗电量大的问题？我对这个问题有几点猜想：
- udp 本身的特点导致的
- kcp 协议设置之初的缺陷
- mkcp 移植引出的bug

另外，我还没有测试过kcptun搭ss的情况，不知道kcptun会不会也这样

**Comment by v2ray** [comment]
mkcp 的内部实现中有一个线程每 50 ms（由 tti 指定）刷新一次，当有一个长连接但没什么数据的时候，它依然会以固定的频率刷新，导致耗电。

之后的版本会修复这个问题。

**Comment by v2ray** [comment]
在 core 中已修复：https://github.com/v2ray/v2ray-core/commit/da9f1a80139977cca88e01c5a2fd665ea3df48d2

**Comment by liberal-boy** [comment]
Actinium 0.6.0 已同步 core的修复，该故障应该已经解决。

**Comment by v2ray** [comment]
更新之后的行为是：

* 当有数据传输时，mkcp 会以 tti ms 的周期进行内部刷新；
* 当没有数据传输（但连接被保持）时，刷新周期会自动下降到 5 秒；

应该可以观察到明显的耗电量减少，但不会比 TCP 更少。

**Comment by v2ray** [comment]
@ToutyRater 请问有后续的测试结果吗？
